# Generated by Django 3.2.6 on 2021-08-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hue", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="light",
            old_name="id",
            new_name="light_id",
        ),
    ]
