name: Linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  black_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: '. --check'

